### ISSUE TITLE
CDATA are skipped

### ISSUE THREAD

**Issue by Amedeo91** [Arzaroth/python_rapidxml#1]
Hi all,

the CDATA are always skipped when trying to parse the xml.

This is because in the document_object.cpp we have this line of code:
(self->base.base.document
     ->parse<rapidxml::parse_no_utf8 | rapidxml::parse_no_data_nodes>)
      (self->base.base.document->allocate_string(text));

Shouldn't be possible to call parse<parse_declaration_node> or parse<parse_full>

Regards,
Amedeo

**Comment by Arzaroth** [comment]
Could you provide an example with expected results ?

**Comment by Amedeo91** [comment]
I want to be able to read what I have inside this CDATA below

<ns2:AdditionalData>
		<ns2:Data TID="AD_1">&lt;![CDATA[{"Cart":{"expirationTime":"2017-04-22T09:40","id":"b469df3b-f626-4fe3-898c-825373e546a2","products":["1223"],"creationTime":"2017-04-21T09:40","totalPrice":{"currencyCode":"EUR","amount":"138.000"}}}]]&gt;</ns2:Data>
	</ns2:AdditionalData>

**Comment by Amedeo91** [comment]
<ns2:AdditionalData>
		<ns2:Data Name="RailKit" TID="AD_1">&lt;![CDATA[{"Cart":{"expirationTime":"2017-04-22T09:40","id":"b469df3b-f626-4fe3-898c-825373e546a2","products":["1223"],"creationTime":"2017-04-21T09:40","totalPrice":{"currencyCode":"EUR","amount":"138.000"}}}]]&gt;</ns2:Data>
	</ns2:AdditionalData>

**Comment by Arzaroth** [comment]
Unless you have very specific needs (i.e. parsing almost-valid xml with braces in attributes), I would use BeautifulSoup4.
While it would be nice to fix this using a **kw on the parse method, I do not intend to do it anytime soon.
If your PR #2 passes CI (given you provide tests for the new functionality), I'll be happy to merge it.

**Comment by Amedeo91** [comment]
@Arzaroth: done

**Comment by Arzaroth** [comment]
Resolved with PR #4
